# Generated by Django 4.2.5 on 2023-09-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
