# Generated by Django 4.2.5 on 2023-10-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
