# Generated by Django 4.2.5 on 2023-10-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posts_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='no_image.png', upload_to='images/'),
        ),
    ]
