# Generated by Django 4.2.5 on 2023-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='images/no_image.png', upload_to='images/'),
        ),
    ]
